#pragma once

//From glfw3.h
#define CACTUS_MOUSE_BUTTON_1         0
#define CACTUS_MOUSE_BUTTON_2         1
#define CACTUS_MOUSE_BUTTON_3         2
#define CACTUS_MOUSE_BUTTON_4         3
#define CACTUS_MOUSE_BUTTON_5         4
#define CACTUS_MOUSE_BUTTON_6         5
#define CACTUS_MOUSE_BUTTON_7         6
#define CACTUS_MOUSE_BUTTON_8         7
#define CACTUS_MOUSE_BUTTON_LAST      CACTUS_MOUSE_BUTTON_8
#define CACTUS_MOUSE_BUTTON_LEFT      CACTUS_MOUSE_BUTTON_1
#define CACTUS_MOUSE_BUTTON_RIGHT     CACTUS_MOUSE_BUTTON_2
#define CACTUS_MOUSE_BUTTON_MIDDLE    CACTUS_MOUSE_BUTTON_3